<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_product</name>
   <tag></tag>
   <elementGuidId>571b14a2-5cc7-4010-9e1b-791e4c4e3749</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@name=&quot;${name}&quot;]/option[@label=&quot;${label}&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@name=&quot;${name}&quot;]/option[@label=&quot;${label}&quot;]</value>
      <webElementGuid>42a8cf53-5759-4ff3-9593-5cedfbdf0358</webElementGuid>
   </webElementProperties>
</WebElementEntity>
