<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_field</name>
   <tag></tag>
   <elementGuidId>11933d54-7df4-4400-8fe3-fd54e0a3ef74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name=&quot;${name}&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name=&quot;${name}&quot;]</value>
      <webElementGuid>0b54dcaa-b366-48a1-a1c0-8fcc79c34667</webElementGuid>
   </webElementProperties>
</WebElementEntity>
